### ISSUE TITLE
--stop-when-sick broken

### ISSUE THREAD

**Issue by Sduby22** [ipid/bupt-ncov-report#11]
RuntimeError: 要上报的数据似乎是破损的，可能网页已经改版。此时无法使用 STOP_WHEN_SICK 功能；上报失败，请手动上报。

但是去掉 --stop-when-sick 后运行正常

**Comment by ipid** [comment]
感谢反馈！这是因为从 2020/6/18 起北邮的上报网站改动了填报的选项，删掉了原有的几个选项，所以代码需要更新。更新到最新的代码（commit 0bf6adf2）就好了。

由于代码尚未实现自动更新，所以需要用户频繁更新，这也是本项目的缺点。有一款十分优秀的 Telegram 机器人提供自动上报服务：https://t.me/buptncovbot，欢迎使用。

**Comment by Sduby22** [comment]
1. 其实我已经更新到了最新版本才出现的问题hhh，昨天没有更新居然还是好的
2. 感谢推荐tgbot! 不用再在服务器上挂了

**Comment by ipid** [comment]
好的！顺便如果继续使用本工具的话，要**至少自己手工填报一遍**。
