### ISSUE TITLE
马上就是一波晨午晚检的填报了

### ISSUE THREAD

**Issue by JarvistFth** [ipid/bupt-ncov-report#12]
学校这个pm马上提新需求了..

**Comment by Sduby22** [comment]
晨午晚检的填报已实装

> 1、线上“每日填报”1次：登录北京邮电大学企业微信号“疫情防控通”中“每日填报”模块，如实完整填写相关信息。截止时间每天中午12点前（晨检）
2、线上“晨午晚检”2次：登录北京邮电大学企业微信号“疫情防控通”中“晨午晚检”模块，如实完整填写相关信息。下午12：00-17：00（午检）；晚上18：00-21：00（晚检）。
