### ISSUE TITLE
字段`sfsfbh`是什么意思呢

### ISSUE THREAD

**Issue by huangbiubiu** [ipid/bupt-ncov-report#15]
我之前每天都在学校手动申报，但是尝试运行代码到

https://github.com/ipid/bupt-ncov-report/blob/da5c66205bf8688f15e1ae7fce84e017bd08f8e2/bupt_ncov_report/program_utils/program_utils.py#L141-L142

就显示`sfsfbh`是`True`，然后提交失败

**Comment by huangbiubiu** [comment]
从[这里](https://www.cnblogs.com/ezhar/p/13913084.html)看起来是`是否省份变化`的意思

**Comment by ipid** [comment]
如果一直都在学校手动签到的话我也不太清楚_(:з」∠)_
学校的字段一直在变动，干脆不要开启 STOP_WHEN_SICK 好了
