### ISSUE TITLE
bug：依赖的 requests 库无法正常工作

### ISSUE THREAD

**Issue by slendermaan** [ipid/bupt-ncov-report#4]
requests.exceptions.SSLError: HTTPSConnectionPool(host=&#x27;app.bupt.edu.cn&#x27;, port=443): Max retries exceeded with url: /uc/wap/login/check (Caused by SSLError(&quot;Can&#x27;t connect to HTTPS URL because the SSL module is not available.&quot;,))
打扰大佬了。就是使用的时候存在这个问题。可以求助一下嘛不好意思。。

**Comment by ipid** [comment]
感谢提供 Issue (｡･ω･｡)ﾉ♡
我谷歌了一下，错误原因可能是使用了 Anaconda 来运行此脚本：https://stackoverflow.com/questions/54135206/requests-caused-by-sslerrorcant-connect-to-https-url-because-the-ssl-module

Anaconda 版的 Python 似乎无法正常加载与 SSL 有关的依赖库。使用原始的 Python，或按照上面的 StackOverflow 里讲的方法来应该能搞定。

**Comment by slendermaan** [comment]
非常感谢你。确实是openssl没有安装导致的!
linux-centos下运行的
yum install openssl
　　yum install openssl-devel
　　cd python3.6.1
　　make && make install
通过这些命令解决了。。
