### ISSUE TITLE
关于地址

### ISSUE THREAD

**Issue by tianmaxingkong12** [ipid/bupt-ncov-report#6]
是这样，每个学校的疫情防控通应该都大同小异，在代码里看到是把昨天的数据用今天的更新，因为今天的是空的，这样地址就没了，请问提交过程中是否出现过问题。

**Comment by ipid** [comment]
这个问题已经注意到了，目前是 WIP 状态。欢迎 Pull Request。

**Comment by ipid** [comment]
2ee4b18 已修复此问题。
