### ISSUE TITLE
最后提交的数据是不是json格式，代码中没注意到把字典转换成json的地方

### ISSUE THREAD

**Issue by tianmaxingkong12** [ipid/bupt-ncov-report#7]

**Comment by ipid** [comment]
不是 JSON 格式。

**Comment by tianmaxingkong12** [comment]
这是我查到的网页源代码，上面标明json格式


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ipid"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月28日(星期六) 中午12:33
收件人:&nbsp;"ipid/bupt-ncov-report"<bupt-ncov-report@noreply.github.com&gt;;
抄送:&nbsp;"天马行空"<1498420415@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ipid/bupt-ncov-report] 最后提交的数据是不是json格式，代码中没注意到把字典转换成json的地方 (#7)





 
不是 JSON 格式。

**Comment by ipid** [comment]
请问可以直接在 GitHub 上回复 issue 吗？从上面的回复看来，似乎发了附件，但是 GitHub 上看不到附件。
