### ISSUE TITLE
我从网站的源代码里找到这个，是不是说明需要以json格式提交，还是字典提交也可以

### ISSUE THREAD

**Issue by tianmaxingkong12** [ipid/bupt-ncov-report#8]
<img width="400" alt="1" src="https://user-images.githubusercontent.com/29156524/77839708-aafbcc00-71b1-11ea-8257-2fad6b1006f8.png">

**Comment by ipid** [comment]
参考：[jQuery.ajax 的文档](https://api.jquery.com/jquery.ajax/#jQuery-ajax-settings)

这里的 dataType: 'JSON'，指的是**所能接受的服务器的返回格式**是 JSON，而不是**所发送的格式**是 JSON。抓包也能得出此结论。

**Comment by tianmaxingkong12** [comment]
好的，感谢



---原始邮件---
发件人: "ipid"<notifications@github.com&gt;
发送时间: 2020年3月29日(周日) 中午11:47
收件人: "ipid/bupt-ncov-report"<bupt-ncov-report@noreply.github.com&gt;;
抄送: "tianmaxingkong12"<1498420415@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [ipid/bupt-ncov-report] 我从网站的源代码里找到这个，是不是说明需要以json格式提交，还是字典提交也可以 (#8)




 
参考：jQuery.ajax 的文档
 
这里的 dataType: 'JSON'，指的是所能接受的服务器的返回格式是 JSON，而不是所发送的格式是 JSON。抓包也能得出此结论。
